# Generated by Django 3.2 on 2024-09-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('desc', models.TextField()),
                ('year', models.IntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='movie_images/')),
            ],
        ),
    ]
