# Generated by Django 3.2 on 2024-10-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle', models.CharField(max_length=240)),
                ('first', models.CharField(max_length=240)),
                ('last', models.CharField(max_length=240)),
                ('username', models.CharField(max_length=240)),
                ('password', models.CharField(max_length=240)),
                ('confirm', models.CharField(max_length=240)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
