# Generated by Django 3.2 on 2024-10-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietimes',
            name='desc',
            field=models.TextField(max_length=240),
        ),
    ]
